codecov:
    branch: master

comment: true

ignore:
    # ignore the entire PredictMD.Cleaning submodule
    - "src/submodules/Cleaning"
    - "src/submodules/Cleaning/**/*"

    # ignore the entire PredictMD.Compilation submodule
    - "src/submodules/Compilation"
    - "src/submodules/Compilation/**/*"

    # ignore the entire PredictMD.GPU submodule
    - "src/submodules/GPU"
    - "src/submodules/GPU/**/*"

    # ignore the entire PredictMD.Server submodule
    - "src/submodules/Server"
    - "src/submodules/Server/**/*"

    # ignore src/toplevel/utils/openbrowserwindow.jl
    # - "src/toplevel/utils/openbrowserwindow.jl"

